name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - master # SİZİN ƏSAS BRANCH-İNİZİN ADI (main və ya master)
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy-edge-functions:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy 'analyzeExamResult' Edge Function
        run: |
          echo "Deploying 'analyzeExamResult' function to project ${{ env.SUPABASE_PROJECT_ID }}"
          supabase functions deploy analyzeExamResult --project-id ${{ env.SUPABASE_PROJECT_ID }} --no-verify-jwt
